"""Add f1 schema with historical data support

Revision ID: 63c9fcc4a4df
Revises: 
Create Date: 2026-01-28 06:41:10.878029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c9fcc4a4df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('circuit_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('locality', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('circuit_id'),
    schema='f1'
    )
    op.create_table('constructors',
    sa.Column('constructor_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('constructor_id'),
    schema='f1'
    )
    op.create_table('drivers',
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('given_name', sa.String(), nullable=False),
    sa.Column('family_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('driver_id'),
    schema='f1'
    )
    op.create_table('seasons',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year'),
    schema='f1'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('constructor_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['f1.constructors.constructor_id'], ),
    sa.ForeignKeyConstraint(['season'], ['f1.seasons.year'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'round', 'constructor_id', name='uq_constructor_standing'),
    schema='f1'
    )
    op.create_index(op.f('ix_f1_constructor_standings_id'), 'constructor_standings', ['id'], unique=False, schema='f1')
    op.create_index(op.f('ix_f1_constructor_standings_season'), 'constructor_standings', ['season'], unique=False, schema='f1')
    op.create_table('driver_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('constructor_id', sa.String(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=True),
    sa.Column('driver_code', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['f1.constructors.constructor_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['f1.drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['season'], ['f1.seasons.year'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'driver_id', 'constructor_id', name='uq_driver_entry'),
    schema='f1'
    )
    op.create_index(op.f('ix_f1_driver_entries_id'), 'driver_entries', ['id'], unique=False, schema='f1')
    op.create_table('driver_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['f1.drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['season'], ['f1.seasons.year'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'round', 'driver_id', name='uq_driver_standing'),
    schema='f1'
    )
    op.create_index(op.f('ix_f1_driver_standings_id'), 'driver_standings', ['id'], unique=False, schema='f1')
    op.create_index(op.f('ix_f1_driver_standings_season'), 'driver_standings', ['season'], unique=False, schema='f1')
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('circuit_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['f1.circuits.circuit_id'], ),
    sa.ForeignKeyConstraint(['season'], ['f1.seasons.year'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'round', name='uq_race_season_round'),
    schema='f1'
    )
    op.create_index(op.f('ix_f1_races_id'), 'races', ['id'], unique=False, schema='f1')
    op.create_index(op.f('ix_f1_races_season'), 'races', ['season'], unique=False, schema='f1')
    op.create_table('user_constructor_follows',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['f1.constructors.constructor_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'constructor_id')
    )
    op.create_table('user_driver_follows',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['f1.drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'driver_id')
    )
    op.create_table('qualifying_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('constructor_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('q1_time', sa.String(), nullable=True),
    sa.Column('q2_time', sa.String(), nullable=True),
    sa.Column('q3_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['f1.constructors.constructor_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['f1.drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['f1.races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', name='uq_quali_result'),
    schema='f1'
    )
    op.create_index(op.f('ix_f1_qualifying_results_id'), 'qualifying_results', ['id'], unique=False, schema='f1')
    op.create_table('race_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('constructor_id', sa.String(), nullable=False),
    sa.Column('grid_position', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('fastest_lap_time', sa.String(), nullable=True),
    sa.Column('fastest_lap_rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['f1.constructors.constructor_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['f1.drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['f1.races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', name='uq_race_result'),
    schema='f1'
    )
    op.create_index(op.f('ix_f1_race_results_id'), 'race_results', ['id'], unique=False, schema='f1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_f1_race_results_id'), table_name='race_results', schema='f1')
    op.drop_table('race_results', schema='f1')
    op.drop_index(op.f('ix_f1_qualifying_results_id'), table_name='qualifying_results', schema='f1')
    op.drop_table('qualifying_results', schema='f1')
    op.drop_table('user_driver_follows')
    op.drop_table('user_constructor_follows')
    op.drop_index(op.f('ix_f1_races_season'), table_name='races', schema='f1')
    op.drop_index(op.f('ix_f1_races_id'), table_name='races', schema='f1')
    op.drop_table('races', schema='f1')
    op.drop_index(op.f('ix_f1_driver_standings_season'), table_name='driver_standings', schema='f1')
    op.drop_index(op.f('ix_f1_driver_standings_id'), table_name='driver_standings', schema='f1')
    op.drop_table('driver_standings', schema='f1')
    op.drop_index(op.f('ix_f1_driver_entries_id'), table_name='driver_entries', schema='f1')
    op.drop_table('driver_entries', schema='f1')
    op.drop_index(op.f('ix_f1_constructor_standings_season'), table_name='constructor_standings', schema='f1')
    op.drop_index(op.f('ix_f1_constructor_standings_id'), table_name='constructor_standings', schema='f1')
    op.drop_table('constructor_standings', schema='f1')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('seasons', schema='f1')
    op.drop_table('drivers', schema='f1')
    op.drop_table('constructors', schema='f1')
    op.drop_table('circuits', schema='f1')
    # ### end Alembic commands ###
