"""Initial tables

Revision ID: bdbbf60ac957
Revises: 
Create Date: 2025-12-13 03:03:30.647577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdbbf60ac957'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constructors',
    sa.Column('constructor_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('constructor_id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('race_name', sa.String(), nullable=False),
    sa.Column('circuit_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_races_id'), 'races', ['id'], unique=False)
    op.create_index(op.f('ix_races_season'), 'races', ['season'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('drivers',
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('given_name', sa.String(), nullable=False),
    sa.Column('family_name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('current_team_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['current_team_id'], ['constructors.constructor_id'], ),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('number')
    )
    op.create_table('user_constructor_follows',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.constructor_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'constructor_id')
    )
    op.create_table('race_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_results_id'), 'race_results', ['id'], unique=False)
    op.create_table('user_driver_follows',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'driver_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_driver_follows')
    op.drop_index(op.f('ix_race_results_id'), table_name='race_results')
    op.drop_table('race_results')
    op.drop_table('user_constructor_follows')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_races_season'), table_name='races')
    op.drop_index(op.f('ix_races_id'), table_name='races')
    op.drop_table('races')
    op.drop_table('constructors')
    # ### end Alembic commands ###
